### ISSUE TITLE
What is .daphne-laptop?

### ISSUE THREAD

**Issue by joostf** [DphnZwp/connect-your-tribe-fdnd-visitekaartje#11]
https://github.com/DphnZwp/connect-your-tribe-fdnd-visitekaartje/blob/317dceec42fc2ec0b3c0ff9667b1d07e895b3337/styles/style.css#L154

**Comment by DphnZwp** [comment]
Het veranderd naar `.daphne-image {`. Ook heb ik `daphne-questions {` veranderd naar `questions-image {`.
