### ISSUE TITLE
Place SVG directly in your HTML?

### ISSUE THREAD

**Issue by joostf** [DphnZwp/connect-your-tribe-fdnd-visitekaartje#9]
https://github.com/DphnZwp/connect-your-tribe-fdnd-visitekaartje/blob/317dceec42fc2ec0b3c0ff9667b1d07e895b3337/index.html#L17

You can add your SVG element directly into your HTML instead of using an image tag. This provides the opportunity to animate the separate elements of your SVG and it saves you from requesting an image from the server.

**Comment by DphnZwp** [comment]
Opgelost,
